slogan: "最怕一生碌碌无为，还说平凡难能可贵."

show_heart: true

show_slogan: true

menu:
  - title: Archives
    url: archives
    intro: "All the articles."
    # icon: "fa fa-archive"
  - title: Categories
    url: categories
    intro: "All the categories."
    # icon: "fa fa-folder"
  - title: Tags
    url: tags
    intro: "All the tags."
    # icon: "fa fa-tags"
  - title: About
    url: about
    intro: "About me."
    # icon: "fa fa-user"
  - title: RSS
    url: atom.xml
    intro: "Subscribe me."
    # icon: "fa fa-user"

links:
  - title: Github
    url: https://github.com/wss981086665
    intro: "My Github address."
    icon: "fa fa-github"
  - title: 微博
    url: https://weibo.com/u/5530988695?is_all=1
    intro: "微博地址."
    icon: "fa fa-weibo"
  - title: RSS
    url: /atom.xml
    intro: "RSS."
    icon: "fa fa-rss"
  # - title: "My LinkedIn"
  #   url: http://www.linkedin.com/in/xxx
  #   intro: "My Linkin account."
  #   icon: "fa fa-linkedin"

widgets:
- search
- category
- tagcloud
- recent_posts
- links

rss: 
fancybox: true
favicon: favicon.png
duoshuo_shortname:


# Analytics (change to yours)
google_analytics:
  enable: true
  siteid: UA-70812759-1
baidu_tongji:
  enable: true
  siteid: cb5448498d7169c668b07c2b255d62c1

# search
#swiftype_key: ZP2ZSuHgipSZfRyU8uTR
